import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:ssg_app/blocs/clock/clock_bloc.dart';
import 'package:ssg_app/data/repositories/task_repo.dart';
import 'package:ssg_app/data/repositories/user_repo.dart';
import 'package:ssg_app/models/Task.dart';
import 'package:ssg_app/utils/api_endpoint.dart';
import 'package:ssg_app/utils/app_colors.dart';
import 'package:ssg_app/utils/app_helpers.dart';
import 'package:ssg_app/utils/app_text_style.dart';
import 'package:ssg_app/widgets/app_alert.dart';
import 'package:ssg_app/widgets/app_button.dart';
import 'package:ssg_app/widgets/app_card.dart';
import 'package:ssg_app/widgets/app_list_component.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

class MyScreen extends StatefulWidget {
  const MyScreen({super.key});

  @override
  State<MyScreen> createState() => _MyScreenState();
}

class _MyScreenState extends State<MyScreen> {
  // Form state variables
  bool isDone = false;
  int? userId;
  int selectedDay = 1;
  int sholatWajib = 1;
  bool sholatTahajud = false;
  int sholatDhuha = 0;
  int sholatRawatib = 0;
  int sholatSunnahLainnya = 0;
  bool tilawahQuran = false;
  bool terjemahQuran = false;
  bool shaumSunnah = false;
  bool shodaqoh = false;
  bool dzikirPagiPetang = false;
  int istighfar1000x = 0;
  int sholawat100x = 0;
  bool menyimakMqPagi = false;
  bool kajianAlhikam = false;
  bool makrifatullah = false;
  bool isLoading = false;

  final TextEditingController istighfarController = TextEditingController();
  final TextEditingController sholawatController = TextEditingController();

  @override
  void initState() {
    super.initState();
    istighfarController.text = istighfar1000x.toString();
    sholawatController.text = sholawat100x.toString();
    AppHelpers.lodaData(
      (data) {
        setState(() {
          userId = data;
          isLoading = false;
        });
      },
      () {
        setState(() {
          isLoading = false;
        });
      },
      mounted,
      UserRepository.getInteger("userId"),
    );
    AppHelpers.lodaData((data){
      setState(() {
        print("isDone: $data");
        isDone = data;
      });
    }, (){
      setState(() {
        isDone = false;
      });
    }, mounted, TaskRepository.getCurrent(userId, selectedDay == 1 ? DateTime(
      DateTime.now().year,
      DateTime.now().month,
      DateTime.now().day + 1
    ) : getSelectedDate()));
  }

  @override
  void dispose() {
    istighfarController.dispose();
    sholawatController.dispose();
    super.dispose();
  }

  DateTime getSelectedDate() {
    final now = DateTime.now();
    return DateTime(
      now.year,
      now.month,
      now.day - (selectedDay - 1),
      now.hour,
      now.minute,
      now.second,
      now.millisecond,
      now.microsecond,
    );
  }

  Future<void> submitData() async {
    setState(() {
      isLoading = true;
    });

    try {
      final selectedDate = getSelectedDate();

      // Update values from text controllers
      istighfar1000x = int.tryParse(istighfarController.text) ?? 0;
      sholawat100x = int.tryParse(sholawatController.text) ?? 0;

      final mutabaahData = MutabaahYaumiyahModel(
        id: '', // This will be generated by the server
        userId: userId.toString(), // Replace with actual user ID
        date: selectedDate,
        sholatWajib: sholatWajib,
        sholatTahajud: sholatTahajud,
        sholatDhuha: sholatDhuha,
        sholatRawatib: sholatRawatib,
        sholatSunnahLainnya: sholatSunnahLainnya,
        tilawahQuran: tilawahQuran,
        terjemahQuran: terjemahQuran,
        shaumSunnah: shaumSunnah,
        shodaqoh: shodaqoh,
        dzikirPagiPetang: dzikirPagiPetang,
        istighfar1000x: istighfar1000x,
        sholawat100x: sholawat100x,
        menyimakMqPagi: menyimakMqPagi,
        // Only include Thursday kajian if it's Thursday
        kajianAlhikam:
            selectedDate.weekday == 4 ? (kajianAlhikam ? 1 : 0) : null,
        makrifatullah:
            selectedDate.weekday == 4 ? (makrifatullah ? 1 : 0) : null,
      );

      final response = await http.post(
        Uri.parse(ApiEndpoint.inputMy), // Replace with your actual API URL
        headers: {
          'Content-Type': 'application/json',
          // Add authorization header if needed
          // 'Authorization': 'Bearer $token',
        },
        body: jsonEncode(mutabaahData.toJson()),
      );

      if (response.statusCode == 200 || response.statusCode == 201) {
        if (mounted) {
          AppAlert.snakBarShow(context, "Data berhasil disimpan");
          AppHelpers.goBack(context);
          setState(() {
            isDone = true;
          });
        }
      } else {
        throw Exception('Failed to save data: ${response.statusCode}');
      }
    } catch (e) {
      if (mounted) {
        AppAlert.snakBarShow(
          context,
          "Anda sudah mengisi mutaba'ah sebelumnya",
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          isLoading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    context.read<ClockBloc>().add(StartClock());
    return Container(
      child: SingleChildScrollView(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            AppCard.fill(
              Padding(
                padding: const EdgeInsets.symmetric(
                  horizontal: 20,
                  vertical: 20,
                ),
                child: ListTile(
                  contentPadding: EdgeInsets.zero,
                  subtitle: BlocBuilder<ClockBloc, ClockState>(
                    builder: (context, state) {
                      return Text(
                        state.time,
                        style: GoogleFonts.spaceMono(
                          fontSize: 15,
                          color: AppColors.lightColor,
                        ),
                      );
                    },
                  ),
                  title: Text(
                    "${AppListComponent.daysName[DateTime.now().weekday]}, ${DateTime.now().day} ${AppListComponent.monthName[DateTime.now().month - 1]} ${DateTime.now().year}",
                    style: GoogleFonts.poppins(color: AppColors.lightColor),
                  ),
                  trailing: Container(
                    padding: const EdgeInsets.symmetric(
                      horizontal: 10,
                      vertical: 5,
                    ),
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(7),
                      color:
                          selectedDay == 1
                              ? AppColors.skyColor
                              : Colors.brown.shade500,
                      shape: BoxShape.rectangle,
                      border: Border.all(color: AppColors.lightColor, width: 1),
                    ),
                    child: Text(
                      selectedDay == 1
                          ? "Tepat Waktu"
                          : (DateTime.now().hour < 8
                              ? "Belum Tepat Waktu"
                              : "Terlambat ${selectedDay - 1} Hari"),
                      style: GoogleFonts.poppins(color: AppColors.lightColor),
                    ),
                  ),
                ),
              ),
              AppColors.primaryColor,
            ),
            AppCard.fill(
              Padding(
                padding: const EdgeInsets.symmetric(
                  horizontal: 10,
                  vertical: 20,
                ),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text(
                          "Mutaba'ah Yaumiyah",
                          style: AppTextStyle.subtitle.copyWith(fontSize: 18),
                        ),
                        Text(
                          "${AppListComponent.daysName[getSelectedDate().weekday]}, ${getSelectedDate().day} ${AppListComponent.monthName[getSelectedDate().month - 1]} ${getSelectedDate().year}",
                          style: AppTextStyle.bodyText.copyWith(fontSize: 14),
                        ),
                      ],
                    ),
                    const SizedBox(height: 10),
                    Container(
                      margin: EdgeInsets.symmetric(vertical: 10),
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(10),
                        color: AppColors.lightColor,
                        shape: BoxShape.rectangle,
                        border: Border.all(
                          color: AppColors.primaryColor,
                          width: 1,
                        ),
                      ),
                      child: DropdownButton(
                        isExpanded: true,
                        underline: SizedBox.shrink(),
                        borderRadius: BorderRadius.circular(10),
                        menuWidth: double.infinity,
                        padding: EdgeInsets.symmetric(horizontal: 8),
                        items: List.generate(7, (index) {
                          final date = DateTime.now().subtract(
                            Duration(days: index),
                          );
                          return DropdownMenuItem(
                            value: index + 1,
                            child: Text(
                              "${date.day} ${AppListComponent.monthName[date.month - 1]} ${date.year}",
                            ),
                          );
                        }),
                        value: selectedDay,
                        onChanged: (value) {
                          setState(() {
                            selectedDay = value!;
                            AppHelpers.lodaData(
                              (data) {
                                setState(() {
                                  isDone = data;
                                });
                              },
                              () {
                                setState(() {
                                  isDone = false;
                                });
                              },
                              mounted,
                              TaskRepository.getCurrent(userId, getSelectedDate()),
                            );
                          });
                        },
                      ),
                    ),
                    SingleChildScrollView(
                      child: Column(
                        children: [
                          Text(
                            "1.1 Sholat Wajib dan Sunnah",
                            style: AppTextStyle.subtitle,
                          ),
                          Container(
                            margin: const EdgeInsets.symmetric(vertical: 10),
                            height: 1,
                            width: double.infinity,
                            color: AppColors.darkColor,
                          ),
                          const SizedBox(height: 10),
                          ListTile(
                            title: Text("Sholat Fardhu"),
                            subtitle: Text("Sholat wajib 5 waktu"),
                            trailing: Container(
                              decoration: BoxDecoration(
                                borderRadius: BorderRadius.circular(7),
                                color: AppColors.lightColor,
                                shape: BoxShape.rectangle,
                                border: Border.all(
                                  color: AppColors.primaryColor,
                                  width: 1,
                                ),
                              ),
                              child: DropdownButton(
                                padding: const EdgeInsets.symmetric(
                                  horizontal: 8,
                                  vertical: 5,
                                ),
                                items: [
                                  DropdownMenuItem(value: 1, child: Text("1")),
                                  DropdownMenuItem(value: 2, child: Text("2")),
                                  DropdownMenuItem(value: 3, child: Text("3")),
                                  DropdownMenuItem(value: 4, child: Text("4")),
                                  DropdownMenuItem(value: 5, child: Text("5")),
                                ],
                                onChanged: (value) {
                                  setState(() {
                                    sholatWajib = value!;
                                  });
                                },
                                value: sholatWajib,
                                borderRadius: BorderRadius.circular(10),
                                isDense: true,
                                underline: SizedBox.shrink(),
                              ),
                            ),
                          ),
                          ListTile(
                            title: Text("Sholat Tahajud & atau Witir"),
                            subtitle: Text("3 rakaat/hari"),
                            trailing: Checkbox(
                              value: sholatTahajud,
                              onChanged: (value) {
                                setState(() {
                                  sholatTahajud = value!;
                                });
                              },
                            ),
                          ),
                          ListTile(
                            title: Text("Sholat Dhuha"),
                            subtitle: Text("4 rakaat"),
                            trailing: Container(
                              decoration: BoxDecoration(
                                borderRadius: BorderRadius.circular(7),
                                color: AppColors.lightColor,
                                shape: BoxShape.rectangle,
                                border: Border.all(
                                  color: AppColors.primaryColor,
                                  width: 1,
                                ),
                              ),
                              child: DropdownButton(
                                padding: const EdgeInsets.symmetric(
                                  horizontal: 8,
                                  vertical: 5,
                                ),
                                items: [
                                  DropdownMenuItem(value: 0, child: Text("0")),
                                  DropdownMenuItem(value: 2, child: Text("2")),
                                  DropdownMenuItem(value: 4, child: Text("4")),
                                  DropdownMenuItem(value: 6, child: Text("6")),
                                  DropdownMenuItem(value: 8, child: Text("8")),
                                  DropdownMenuItem(
                                    value: 10,
                                    child: Text("10"),
                                  ),
                                  DropdownMenuItem(
                                    value: 12,
                                    child: Text("12"),
                                  ),
                                ],
                                onChanged: (value) {
                                  setState(() {
                                    sholatDhuha = value!;
                                  });
                                },
                                value: sholatDhuha,
                                borderRadius: BorderRadius.circular(10),
                                isDense: true,
                                underline: SizedBox.shrink(),
                              ),
                            ),
                          ),
                          ListTile(
                            title: Text("Sholat Rawatib"),
                            subtitle: Text("10 rakaat"),
                            trailing: Container(
                              decoration: BoxDecoration(
                                borderRadius: BorderRadius.circular(7),
                                color: AppColors.lightColor,
                                shape: BoxShape.rectangle,
                                border: Border.all(
                                  color: AppColors.primaryColor,
                                  width: 1,
                                ),
                              ),
                              child: DropdownButton(
                                padding: const EdgeInsets.symmetric(
                                  horizontal: 8,
                                  vertical: 5,
                                ),
                                items: [
                                  DropdownMenuItem(value: 0, child: Text("0")),
                                  DropdownMenuItem(value: 2, child: Text("2")),
                                  DropdownMenuItem(value: 4, child: Text("4")),
                                  DropdownMenuItem(value: 6, child: Text("6")),
                                  DropdownMenuItem(value: 8, child: Text("8")),
                                  DropdownMenuItem(
                                    value: 10,
                                    child: Text("10"),
                                  ),
                                  DropdownMenuItem(
                                    value: 12,
                                    child: Text("12"),
                                  ),
                                ],
                                onChanged: (value) {
                                  setState(() {
                                    sholatRawatib = value!;
                                  });
                                },
                                value: sholatRawatib,
                                borderRadius: BorderRadius.circular(10),
                                isDense: true,
                                underline: SizedBox.shrink(),
                              ),
                            ),
                          ),
                          ListTile(
                            title: Text("Sholat Sunnah"),
                            subtitle: Text("Lainnya 6 rakaat"),
                            trailing: Container(
                              decoration: BoxDecoration(
                                borderRadius: BorderRadius.circular(7),
                                color: AppColors.lightColor,
                                shape: BoxShape.rectangle,
                                border: Border.all(
                                  color: AppColors.primaryColor,
                                  width: 1,
                                ),
                              ),
                              child: DropdownButton(
                                padding: const EdgeInsets.symmetric(
                                  horizontal: 8,
                                  vertical: 5,
                                ),
                                items: [
                                  DropdownMenuItem(value: 0, child: Text("0")),
                                  DropdownMenuItem(value: 2, child: Text("2")),
                                  DropdownMenuItem(value: 4, child: Text("4")),
                                  DropdownMenuItem(value: 6, child: Text("6")),
                                  DropdownMenuItem(value: 8, child: Text("8")),
                                  DropdownMenuItem(
                                    value: 10,
                                    child: Text("10"),
                                  ),
                                  DropdownMenuItem(
                                    value: 12,
                                    child: Text("12"),
                                  ),
                                ],
                                onChanged: (value) {
                                  setState(() {
                                    sholatSunnahLainnya = value!;
                                  });
                                },
                                value: sholatSunnahLainnya,
                                borderRadius: BorderRadius.circular(10),
                                isDense: true,
                                underline: SizedBox.shrink(),
                              ),
                            ),
                          ),
                          SizedBox(height: 10),
                          Text(
                            "1.2 Aktivitas Qur'an",
                            style: AppTextStyle.subtitle,
                          ),
                          Container(
                            margin: const EdgeInsets.symmetric(vertical: 10),
                            height: 1,
                            width: double.infinity,
                            color: AppColors.darkColor,
                          ),
                          ListTile(
                            title: Text("Tilawah"),
                            subtitle: Text("1 Halaman"),
                            trailing: Checkbox(
                              value: tilawahQuran,
                              onChanged: (value) {
                                setState(() {
                                  tilawahQuran = value!;
                                });
                              },
                            ),
                          ),
                          ListTile(
                            title: Text("Tarjamah"),
                            subtitle: Text("1 Halaman"),
                            trailing: Checkbox(
                              value: terjemahQuran,
                              onChanged: (value) {
                                setState(() {
                                  terjemahQuran = value!;
                                });
                              },
                            ),
                          ),

                          SizedBox(height: 10),
                          Text(
                            "1.3 Aktivitas Sunnah",
                            style: AppTextStyle.subtitle,
                          ),
                          Container(
                            margin: const EdgeInsets.symmetric(vertical: 10),
                            height: 1,
                            width: double.infinity,
                            color: AppColors.darkColor,
                          ),
                          ListTile(
                            title: Text("Shaum Sunnah"),
                            subtitle: Text("(3x/bulan)"),
                            trailing: Checkbox(
                              value: shaumSunnah,
                              onChanged: (value) {
                                setState(() {
                                  shaumSunnah = value!;
                                });
                              },
                            ),
                          ),
                          ListTile(
                            title: Text("Shodaqoh Maal"),
                            trailing: Checkbox(
                              value: shodaqoh,
                              onChanged: (value) {
                                setState(() {
                                  shodaqoh = value!;
                                });
                              },
                            ),
                          ),
                          ListTile(
                            title: Text("Dzikir"),
                            subtitle: Text("Pagi / Petang"),
                            trailing: Checkbox(
                              value: dzikirPagiPetang,
                              onChanged: (value) {
                                setState(() {
                                  dzikirPagiPetang = value!;
                                });
                              },
                            ),
                          ),
                          ListTile(
                            title: Text("Istoghfar"),
                            subtitle: Text("x 1000"),
                            trailing: Container(
                              height: 40,
                              width: 60,
                              child: TextField(
                                controller: istighfarController,
                                keyboardType: TextInputType.number,
                                decoration: InputDecoration(
                                  border: OutlineInputBorder(
                                    borderRadius: BorderRadius.circular(7),
                                    borderSide: BorderSide(
                                      color: AppColors.primaryColor,
                                      width: 1,
                                    ),
                                  ),
                                  contentPadding: const EdgeInsets.symmetric(
                                    horizontal: 10,
                                    vertical: 5,
                                  ),
                                ),
                              ),
                            ),
                          ),
                          ListTile(
                            title: Text("Sholawat"),
                            subtitle: Text("x 100"),
                            trailing: Container(
                              height: 40,
                              width: 60,
                              child: TextField(
                                controller: sholawatController,
                                keyboardType: TextInputType.number,
                                decoration: InputDecoration(
                                  border: OutlineInputBorder(
                                    borderRadius: BorderRadius.circular(7),
                                    borderSide: BorderSide(
                                      color: AppColors.primaryColor,
                                      width: 1,
                                    ),
                                  ),
                                  contentPadding: const EdgeInsets.symmetric(
                                    horizontal: 10,
                                    vertical: 5,
                                  ),
                                ),
                              ),
                            ),
                          ),
                          SizedBox(height: 10),
                          Text(
                            "2.1 Menyimak Kajian",
                            style: AppTextStyle.subtitle,
                          ),
                          Container(
                            margin: const EdgeInsets.symmetric(vertical: 10),
                            height: 1,
                            width: double.infinity,
                            color: AppColors.darkColor,
                          ),
                          ListTile(
                            title: Text("Menyimak MQ"),
                            subtitle: Text("Pagi"),
                            trailing: Checkbox(
                              value: menyimakMqPagi,
                              onChanged: (value) {
                                setState(() {
                                  menyimakMqPagi = value!;
                                });
                              },
                            ),
                          ),

                          if (getSelectedDate().weekday == 4)
                            ListTile(
                              title: Text("Menyimak Kajian"),
                              subtitle: Text("Al-Hikam"),
                              trailing: Checkbox(
                                value: kajianAlhikam,
                                onChanged: (value) {
                                  setState(() {
                                    kajianAlhikam = value!;
                                  });
                                },
                              ),
                            ),
                          if (getSelectedDate().weekday == 4)
                            ListTile(
                              title: Text("Menyimak Kajian"),
                              subtitle: Text("Ma'rifatullah"),
                              trailing: Checkbox(
                                value: makrifatullah,
                                onChanged: (value) {
                                  setState(() {
                                    makrifatullah = value!;
                                  });
                                },
                              ),
                            ),
                        ],
                      ),
                    ),
                    const SizedBox(height: 10),
                    Container(
                      margin: const EdgeInsets.symmetric(
                        vertical: 20,
                        horizontal: 10,
                      ),
                      child: BlocBuilder<ClockBloc, ClockState>(
                        builder: (context, state) {
                          return AppButton(
                            text: isLoading ? "MENYIMPAN..." : (isDone
                                ? "TERSIMPAN"
                                : "SIMPAN"),
                            onPressedButton:
                                isLoading
                                    ? null
                                    : () {
                                      if (DateTime.now().hour > 8 && isDone == false) {
                                        AppAlert.showAlertDialog(
                                          context,
                                          "Perhatian! $isDone",
                                          "Yakin ingin menyimpan data ini? pastikan aktivitas yang diisi sudah benar",
                                          "BATAL",
                                          "OK",
                                          null,
                                          () => submitData(),
                                          AppColors.lightColor,
                                          AppColors.primaryColor,
                                          AppColors.lightColor,
                                          AppColors.accentColor,
                                        );
                                      }
                                    },
                            fullWidth: true,
                            bgColor:
                                DateTime.now().hour < 8
                                    ? Colors.grey[600]
                                    : (isDone ? AppColors.tangledColor : AppColors.primaryColor),
                          ).build();
                        },
                      ),
                    ),
                  ],
                ),
              ),
              AppColors.milkFrothColor,
            ),
          ],
        ),
      ),
    );
  }
}
